name: VS Code

on:
  push:
    paths:
      - 'src/VSCode/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'src/VSCode/package-lock.json'
    
    - name: Install dependencies
      run: |
        cd src/VSCode
        npm ci
    
    - name: Lint
      run: |
        cd src/VSCode
        npm run lint
    
    - name: Build
      run: |
        cd src/VSCode
        npm run compile
    
    - name: Package Extension
      run: |
        cd src/VSCode
        npm run package
    
    - name: Upload VSIX
      uses: actions/upload-artifact@v3
      with:
        name: VSCode-Extension
        path: src/VSCode/*.vsix
